server:
  port: 8080
#  tomcat:
#    access-log-enabled: true
#    access-log-pattern: "%h %l %u %t \"%r\" %s %b"

spring:
  datasource:
    url: jdbc:h2:file:./data/urls
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: DEBUG

